

import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const hljsPkgDir = path.dirname(require.resolve('highlight.js/package.json'));
const outDir = path.resolve(import.meta.dirname, '..', 'frontend', 'vendor', 'hljs-es');
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

function wrapEsm(cjsSource) {
  return `// Generated by scripts/build-hljs.mjs — CommonJS source wrapped as ESM.
const __module = { exports: {} };
(function (module, exports) {
${cjsSource}
})(__module, __module.exports);
export default __module.exports;
`;
}


const coreSrc = fs.readFileSync(path.join(hljsPkgDir, 'lib', 'core.js'), 'utf8');
fs.writeFileSync(path.join(outDir, 'core.js'), wrapEsm(coreSrc));

const LANGS = [
  'javascript', 'typescript', 'python', 'json', 'bash', 'xml', 'css',
  'markdown', 'sql', 'yaml', 'ini', 'rust', 'go', 'java', 'csharp', 'cpp', 'php', 'ruby', 'diff',
];
for (const lang of LANGS) {
  const src = fs.readFileSync(path.join(hljsPkgDir, 'lib', 'languages', `${lang}.js`), 'utf8');
  fs.writeFileSync(path.join(outDir, `${lang}.js`), wrapEsm(src));
}

console.log(`Wrote ${LANGS.length + 1} ESM files to ${outDir}`);
